apiVersion: v1
metadata:
  name: {{ $.Chart.Name }}-secret
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
kind: Secret
type: Opaque
data:
  # Secret env variables
  {{- range $key, $value := .Values.private_env_variables }}
  {{ $key }}: {{ $value | b64enc}}
  {{- end }}